# Generated by Django 4.2.7 on 2023-11-22 09:28

from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields
import marketers.choices
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=64)),
                ('fiscal_name', models.CharField(max_length=64, unique=True)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fee_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('fee', djmoney.models.fields.MoneyField(decimal_places=6, max_digits=14)),
                ('max_consume', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Marketer',
            },
            bases=(models.Model, marketers.choices.MarketerStatus),
        ),
    ]
