# Generated by Django 4.2.7 on 2023-11-22 09:34

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='max_consume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
