# Generated by Django 4.2.7 on 2023-11-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
        ("marketers", "0002_alter_marketer_email_alter_marketer_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketer",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketers",
                to="addresses.address",
            ),
            preserve_default=False,
        ),
    ]
