# Generated by Django 4.2.7 on 2023-11-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('marketers', '0003_marketer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketers', to='addresses.address'),
        ),
    ]
