# Generated by Django 4.2.7 on 2023-11-24 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import margins.choices
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('type', models.CharField(choices=[('rate_type', 'Rate Type'), ('consume_range', 'Consume Range')], max_length=13)),
                ('min_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_margin', models.DecimalField(decimal_places=2, default=100, max_digits=14)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin', to='rates.rate')),
            ],
            options={
                'verbose_name': 'Margin',
            },
            bases=(models.Model, margins.choices.MarginStatus),
        ),
    ]
