# Generated by Django 4.2.7 on 2023-11-16 10:49

import clients.choices
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('bank_account_holder', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('fiscal_address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('fiscal_name', models.CharField(max_length=256)),
                ('cif', models.CharField(max_length=10, unique=True)),
                ('alias', models.CharField(max_length=64, unique=True)),
                ('client_type', models.CharField(choices=[('company', 'company'), ('self-employed', 'self-employed'), ('particular', 'particular'), ('community_owners', 'community_owners')], max_length=20)),
                ('invoice_notification_type', models.CharField(choices=[('email', 'email'), ('postal', 'postal')], max_length=20)),
                ('invoice_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice_postal', models.CharField(blank=True, max_length=64, null=True)),
                ('is_renewable', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
            ],
            options={
                'verbose_name': 'Client',
                'permissions': (('assign_task', 'Assign task'),),
                'unique_together': {('channel', 'cif')},
            },
            bases=(clients.choices.ClientStatus, models.Model),
        ),
    ]
