# Generated by Django 4.2.7 on 2023-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('company', 'Company'), ('self-employed', 'Self Employed'), ('particular', 'Particular'), ('community-owners', 'Community Owners')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('postal', 'Postal')], max_length=20),
        ),
    ]
