# Generated by Django 4.2.7 on 2023-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('clients', '0003_remove_client_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('channel', 'cif')},
        ),
        migrations.AlterField(
            model_name='client',
            name='alias',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('channel', 'cif'), ('channel', 'alias')},
        ),
    ]
