# Generated by Django 4.2.7 on 2023-11-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('clients', '0004_alter_client_unique_together_alter_client_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='channels.channel'),
        ),
    ]
