# Generated by Django 4.2.7 on 2023-11-29 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields
import supply_points.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channel_bank_account_holder_and_more'),
        ('clients', '0006_alter_client_bank_account_holder_and_more'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('bank_account_holder', models.CharField(max_length=255, null=True)),
                ('bank_account_number', models.CharField(max_length=255, null=True)),
                ('fiscal_address', models.CharField(max_length=255, null=True)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=11)),
                ('cups', models.CharField(max_length=124)),
                ('alias', models.CharField(max_length=128, null=True)),
                ('is_renewable', models.BooleanField(default=False)),
                ('max_available_power', models.IntegerField(blank=True, null=True)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('counter_type', models.CharField(choices=[('normal', 'Normal'), ('telematic', 'Telematic')], max_length=11)),
                ('counter_property', models.CharField(choices=[('self', 'Self'), ('marketer', 'Marketer'), ('other', 'Other')], max_length=11)),
                ('counter_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('counter_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_points', to='addresses.address')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_points', to='channels.channel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_points', to='clients.client')),
            ],
            options={
                'verbose_name': 'SupplyPoint',
                'unique_together': {('channel', 'cups')},
            },
            bases=(supply_points.choices.SupplyPointStatus, models.Model),
        ),
    ]
