# Generated by Django 4.2.7 on 2023-11-29 11:15

import contracts.choices
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('rates', '0002_rate_commission'),
        ('clients', '0005_alter_client_channel'),
        ('saving_studies', '0002_savingstudy_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('incomplete', 'Incomplete'), ('requested', 'Requested'), ('waiting-marketer', 'Waiting Marketer'), ('waiting-client-sign', 'Waiting Client Sign'), ('signed', 'Signed'), ('activated', 'Activated'), ('finished', 'Finished'), ('marketer-issue', 'Marketer Issue'), ('distributor-issue', 'Distributor Issue'), ('cancelled', 'Cancelled')], default='incomplete', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('power_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('signature_first_name', models.CharField(max_length=128)),
                ('signature_last_name', models.CharField(max_length=128)),
                ('signature_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('signature_email', models.CharField(blank=True, max_length=256, null=True)),
                ('signature_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='channels.channel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rates.rate')),
                ('saving_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='saving_studies.savingstudy')),
            ],
            options={
                'verbose_name': 'Contract',
            },
            bases=(models.Model, contracts.choices.ContractStatus),
        ),
    ]
