# Generated by Django 4.2.7 on 2023-11-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_points", "0001_initial"),
        ("contracts", "0002_alter_contract_signature_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="supply_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="supply_points.supplypoint",
            ),
            preserve_default=False,
        ),
    ]
