# Generated by Django 4.2.7 on 2023-11-23 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import rates.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_types', '0002_alter_ratetype_max_power_alter_ratetype_min_power'),
        ('marketers', '0002_alter_marketer_email_alter_marketer_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=11)),
                ('price_type', models.CharField(choices=[('fixed_fixed', 'Fixed'), ('fixed_base', 'Base'), ('indexed', 'Indexed')], max_length=11)),
                ('max_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_price_1', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_2', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_3', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_4', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_5', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_6', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_1', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_2', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_3', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_4', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_5', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_6', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('fixed_term_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('permanency', models.BooleanField()),
                ('length', models.IntegerField()),
                ('is_full_renewable', models.BooleanField(blank=True, null=True)),
                ('compensation_surplus', models.BooleanField(blank=True, null=True)),
                ('compensation_surplus_value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='marketers.marketer')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rate_types.ratetype')),
            ],
            options={
                'verbose_name': 'Rate',
            },
            bases=(models.Model, rates.choices.RateStatus),
        ),
    ]
