# Generated by Django 4.2.7 on 2023-11-30 12:47

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_rate_fixed_term_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='compensation_surplus_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='compensation_surplus_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
