# Generated by Django 4.2.7 on 2023-12-12 08:45

from django.db import migrations, models
import django.utils.timezone
import energy_costs.choices
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('concept', models.CharField(max_length=256, unique=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
            options={
                'verbose_name': 'EnergyCost',
            },
            bases=(models.Model, energy_costs.choices.EnergyCostStatus),
        ),
    ]
