# Generated by Django 4.2.7 on 2023-12-05 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields
import suggested_rates.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channel_bank_account_holder_and_more'),
        ('saving_studies', '0004_alter_savingstudy_client_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_selected', models.BooleanField(default=False)),
                ('marketer_name', models.CharField(max_length=256)),
                ('has_contractual_commitment', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('rate_name', models.CharField(max_length=256)),
                ('is_full_renewable', models.BooleanField()),
                ('has_net_metering', models.BooleanField()),
                ('net_metering_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_margin_type', models.CharField(choices=[('rate_type', 'Rate type'), ('consume_range', 'Consume range')], max_length=13)),
                ('min_profit_margin_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('min_profit_margin', djmoney.models.fields.MoneyField(decimal_places=6, max_digits=14)),
                ('max_profit_margin_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('max_profit_margin', djmoney.models.fields.MoneyField(decimal_places=6, max_digits=14)),
                ('applied_profit_margin_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('applied_profit_margin', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('energy_price_1_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_1', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_2_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_2', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_3_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_3', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_4_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_4', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_5_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_5', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energy_price_6_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_6', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_1_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_1', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_2_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_2', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_3_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_3', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_4_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_4', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_5_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_5', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('power_price_6_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_6', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('fixed_term_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('fixed_term_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('price_type', models.CharField(choices=[('fixed_fixed', 'Fixed'), ('fixed_base', 'Base'), ('indexed', 'Indexed')], max_length=11)),
                ('final_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('final_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('fixed_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_costs_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('other_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ie_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('ie_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ih_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('ih_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva_cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('iva_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_commission_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('total_commission', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('theoretical_commission_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('theoretical_commission', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_costs_commission_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('other_costs_commission', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saving_relative_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('saving_relative', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saving_absolute_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('saving_absolute', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
                ('saving_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_rates', to='saving_studies.savingstudy')),
            ],
            options={
                'verbose_name': 'SuggestedRate',
            },
            bases=(models.Model, suggested_rates.choices.SuggestedRateStatus),
        ),
    ]
