# Generated by Django 4.2.7 on 2023-12-05 12:56

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedrate',
            name='net_metering_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='suggestedrate',
            name='net_metering_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
    ]
