# Generated by Django 4.2.7 on 2023-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_rates', '0002_suggestedrate_net_metering_value_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedrate',
            name='profit_margin_type',
            field=models.CharField(choices=[('rate_type', 'Rate Type'), ('consume_range', 'Consume Range')], max_length=13),
        ),
    ]
