# Generated by Django 4.2.7 on 2023-12-04 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import invoices.choices
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_alter_channel_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'Pending payment'), ('payed', 'Payed'), ('canceled', 'Canceled')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('invoice_date', models.DateField()),
                ('cif', models.CharField(max_length=10)),
                ('base_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('base_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('vat_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('vat', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Invoice',
            },
            bases=(models.Model, invoices.choices.InvoiceStatus),
        ),
    ]
