# Generated by Django 4.2.7 on 2023-11-27 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import model_utils.fields
import saving_studies.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_types', '0002_alter_ratetype_max_power_alter_ratetype_min_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='in-progress', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=256)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=11)),
                ('is_existing_client', models.BooleanField(default=False)),
                ('is_from_sips', models.BooleanField(default=False)),
                ('is_compare_conditions', models.BooleanField(default=False)),
                ('cups', models.CharField(max_length=124)),
                ('analyzed_days', models.IntegerField(blank=True, null=True)),
                ('current_marketer', models.CharField(blank=True, max_length=124, null=True)),
                ('client_type', models.CharField(choices=[('company', 'Company'), ('self-employed', 'Self Employed'), ('particular', 'Particular'), ('community-owners', 'Community Owners')], max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=124, null=True)),
                ('client_nif', models.CharField(blank=True, max_length=10, null=True)),
                ('consumption_p1', models.IntegerField(blank=True, null=True)),
                ('consumption_p2', models.IntegerField(blank=True, null=True)),
                ('consumption_p3', models.IntegerField(blank=True, null=True)),
                ('consumption_p4', models.IntegerField(blank=True, null=True)),
                ('consumption_p5', models.IntegerField(blank=True, null=True)),
                ('consumption_p6', models.IntegerField(blank=True, null=True)),
                ('annual_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('energy_price_1_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_1', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('energy_price_2_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_2', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('energy_price_3_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_3', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('energy_price_4_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_4', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('energy_price_5_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_5', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('energy_price_6_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('energy_price_6', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_price_1_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_1', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_price_2_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_2', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_price_3_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_3', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_price_4_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_4', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_price_5_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_5', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('power_price_6_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('power_price_6', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fixed_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('fixed_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('other_cost_kwh_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('other_cost_kwh', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('other_cost_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('other_cost_eur_month_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True)),
                ('other_cost_eur_month', djmoney.models.fields.MoneyField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('current_rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saving_studies', to='rate_types.ratetype')),
            ],
            options={
                'verbose_name': 'SavingStudy',
            },
            bases=(models.Model, saving_studies.choices.SavingStudyStatus),
        ),
    ]
