# Generated by Django 4.2.7 on 2023-11-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("saving_studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingstudy",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="channels.channel"
            ),
            preserve_default=False,
        ),
    ]
