# Generated by Django 4.2.7 on 2023-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving_studies', '0003_remove_savingstudy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstudy',
            name='client_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('self-employed', 'Self Employed'), ('particular', 'Particular'), ('community-owners', 'Community Owners')], max_length=20, null=True),
        ),
    ]
