# Generated by Django 4.2.7 on 2023-11-24 13:49

import commissions.choices
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_types', '0002_alter_ratetype_max_power_alter_ratetype_min_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=124)),
                ('percentage_test_commission', models.IntegerField(blank=True, null=True)),
                ('range_type', models.CharField(choices=[('power', 'Power'), ('consumption', 'Consumption')], max_length=11)),
                ('rate_type_segmentation', models.BooleanField(blank=True, null=True)),
                ('min_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_power', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('test_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='rate_types.ratetype')),
            ],
            options={
                'verbose_name': 'Commission',
            },
            bases=(models.Model, commissions.choices.CommissionStatus),
        ),
    ]
