# Generated by Django 4.2.7 on 2023-12-01 12:04

import costs.choices
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('mandatory', models.BooleanField()),
                ('client_types', models.JSONField(verbose_name='ClientTypes')),
                ('max_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('eur/month', 'eur/month'), ('percentage', 'percentage'), ('eur/kwh', 'eur/kwh')], max_length=11)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'OtherCost',
            },
            bases=(models.Model, costs.choices.OtherCostStatus),
        ),
    ]
