# Generated by Django 4.2.7 on 2023-12-04 11:36

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_othercost_extra_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercost',
            name='extra_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='othercost',
            name='extra_fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
