# Generated by Django 4.2.7 on 2023-11-22 09:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import rate_types.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=256)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=11)),
                ('max_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_power', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'RateType',
            },
            bases=(models.Model, rate_types.choices.RateTypeStatus),
        ),
    ]
