# Generated by Django 4.2.7 on 2023-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetype',
            name='max_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='min_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
